name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run build
      - name: Check build
        run: npm run deploy
