name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Git config
        run: git config --global user.email "${{ github.actor }}@users.noreply.github.com" && git config --global user.name "${{ github.actor }}"
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Check deploy
        run: npm run deploy
