name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Deploy react to gh-pages
        uses: alainQtec/deploy-react-to-ghpages@1.0.0-beta.2
